name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: update
      run: ./scripts/feeds update -a
    - name: install
      run: ./scripts/feeds install -a
    - name: make
      run: make
