name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-18.04

    steps:
    - uses: actions/checkout@v3
    - name: ./scripts/feeds update -a
      run: ./scripts/feeds update -a
    -name: ./scripts/feeds install -a
      run: ./scripts/feeds install -a
    - name: make
      run: make
